#! /bin/sh
removeFile=rm-mkhtml

echo "Beginning Install for mkhtml..."
mkdir -v /var/local/mkhtml
cp -v -R ./var-files/* /var/local/mkhtml
cp -v ./mkhtml /usr/local/bin
cp -v ./$removeFile /usr/local/bin
echo "Finished Installing mkhtml"
echo "Remove mkhtml by running '$removeFile'"
exit 0
